"""add_dixon_coles_and_combo_fields

Revision ID: ff0b48183001
Revises: 
Create Date: 2026-01-14 15:16:32.244676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff0b48183001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('predictions', sa.Column('prob_1x', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('prob_12', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('prob_x2', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('dc_prediction', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('dc_confidence', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_over_25', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_over_25', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_under_25', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_btts', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_btts', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_btts', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('best_combo_prediction', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('best_combo_confidence', sa.Float(), nullable=True))
    op.add_column('predictions', sa.Column('combo_predictions', sa.JSON(), nullable=True))
    op.add_column('predictions', sa.Column('dc_actual', sa.String(), nullable=True))
    op.add_column('predictions', sa.Column('dc_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_over_25_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_over_25_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_over_25_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_over_25_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_under_25_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_under_25_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_btts_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_1_btts_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_btts_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_2_btts_correct', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_btts_actual', sa.Boolean(), nullable=True))
    op.add_column('predictions', sa.Column('combo_x_btts_correct', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('predictions', 'combo_x_btts_correct')
    op.drop_column('predictions', 'combo_x_btts_actual')
    op.drop_column('predictions', 'combo_2_btts_correct')
    op.drop_column('predictions', 'combo_2_btts_actual')
    op.drop_column('predictions', 'combo_1_btts_correct')
    op.drop_column('predictions', 'combo_1_btts_actual')
    op.drop_column('predictions', 'combo_x_under_25_correct')
    op.drop_column('predictions', 'combo_x_under_25_actual')
    op.drop_column('predictions', 'combo_2_over_25_correct')
    op.drop_column('predictions', 'combo_2_over_25_actual')
    op.drop_column('predictions', 'combo_1_over_25_correct')
    op.drop_column('predictions', 'combo_1_over_25_actual')
    op.drop_column('predictions', 'dc_correct')
    op.drop_column('predictions', 'dc_actual')
    op.drop_column('predictions', 'combo_predictions')
    op.drop_column('predictions', 'best_combo_confidence')
    op.drop_column('predictions', 'best_combo_prediction')
    op.drop_column('predictions', 'combo_x_btts')
    op.drop_column('predictions', 'combo_2_btts')
    op.drop_column('predictions', 'combo_1_btts')
    op.drop_column('predictions', 'combo_x_under_25')
    op.drop_column('predictions', 'combo_2_over_25')
    op.drop_column('predictions', 'combo_1_over_25')
    op.drop_column('predictions', 'dc_confidence')
    op.drop_column('predictions', 'dc_prediction')
    op.drop_column('predictions', 'prob_x2')
    op.drop_column('predictions', 'prob_12')
    op.drop_column('predictions', 'prob_1x')
    # ### end Alembic commands ###
